###
POST {{host}}/auth/login
Content-Type: application/json
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36

{
  "username":"admin",
  "password":"123"
}

###

GET {{host}}/api/whoami
Authorization: {{token}}
Content-Type: application/json

###
