--- Initialize Table and Data

DROP TABLE IF EXISTS "authority";
CREATE TABLE "authority" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY (start with 1) NOT NULL,
    "name" character varying(255),
    CONSTRAINT "authority_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

DROP TABLE IF EXISTS "users";
CREATE TABLE "users" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY (start with 1) NOT NULL,
    "email" character varying(255),
    "enabled" boolean,
    "first_name" character varying(255),
    "last_name" character varying(255),
    "last_password_reset_date" timestamp,
    "password" character varying(255),
    "phone_number" character varying(255),
    "username" character varying(255),
    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

DROP TABLE IF EXISTS "user_authority";
CREATE TABLE "public"."user_authority" (
    "user_id" bigint NOT NULL,
    "authority_id" bigint NOT NULL,
    CONSTRAINT "fkgvxjs381k6f48d5d2yi11uh89" FOREIGN KEY (authority_id) REFERENCES authority(id) NOT DEFERRABLE,
    CONSTRAINT "fkhi46vu7680y1hwvmnnuh4cybx" FOREIGN KEY (user_id) REFERENCES users(id) NOT DEFERRABLE
) WITH (oids = false);

INSERT INTO users (id, username, password, first_name, last_name, email, phone_number, enabled, last_password_reset_date) VALUES (1, 'user', '$2a$04$Vbug2lwwJGrvUXTj6z7ff.97IzVBkrJ1XfApfGNl.Z695zqcnPYra', 'Fan', 'Jin', 'user@example.com', '+1234567890', true, '2017-10-01 21:58:58.508-07');
INSERT INTO users (id, username, password, first_name, last_name, email, phone_number, enabled, last_password_reset_date) VALUES (2, 'admin', '$2a$04$Vbug2lwwJGrvUXTj6z7ff.97IzVBkrJ1XfApfGNl.Z695zqcnPYra', 'Jing', 'Xiao', 'admin@example.com', '+0987654321', true, '2017-10-01 18:57:58.508-07');

INSERT INTO authority (id, name) VALUES (1, 'ROLE_USER');
INSERT INTO authority (id, name) VALUES (2, 'ROLE_ADMIN');

INSERT INTO user_authority (user_id, authority_id) VALUES (1, 1);
INSERT INTO user_authority (user_id, authority_id) VALUES (2, 1);
INSERT INTO user_authority (user_id, authority_id) VALUES (2, 2);
